// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElRow: typeof import('element-plus/es')['ElRow']
    Empty: typeof import('./src/components/Editor/src/Empty.vue')['default']
    LayoutHeader: typeof import('./src/components/layout/LayoutHeader.vue')['default']
    Loading: typeof import('./src/components/Editor/src/loading.vue')['default']
    Main: typeof import('./src/components/Editor/src/main.vue')['default']
    MainHeader: typeof import('./src/components/layout/MainHeader.vue')['default']
    Mention: typeof import('./src/components/Editor/src/mention.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
